export default defineAppConfig({
  pages: [
    'pages/login/index',
    'pages/role-select/index',
    'pages/home/index',
    'pages/progress/index',
    'pages/mine/index',
    'pages/demand-detail/index',
    'pages/apply-success/index',
    'pages/resume/index',
    'pages/verify/index',
    'pages/publish-success/index',
    'pages/parent-demand-detail/index',
    'pages/teacher-detail/index',
    'pages/privacy/index',
    'pages/agreement/index',
    'pages/contact/index',
    'pages/notifications/index',
    // 管理员后台（隐藏入口，不走 tabBar）
    'pages/admin/login/index',
    'pages/admin/dashboard/index',
    'pages/admin/orders/index',
    'pages/admin/order-detail/index',
    'pages/admin/deliveries/index',
    'pages/admin/verifications/index',
    'pages/admin/fees/index',
    'pages/admin/demands/index',
    'pages/admin/applications/index',
    'pages/admin/query/index',
    'pages/admin/settings/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#f5f8f6',
    navigationBarTitleText: '小小陪伴帮',
    navigationBarTextStyle: 'black',
    backgroundColor: '#f5f8f6',
  },
  tabBar: {
    color: '#86909c',
    selectedColor: '#18a06b',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home-selected.png',
      },
      {
        pagePath: 'pages/progress/index',
        text: '进度',
        iconPath: 'assets/tabbar/progress.png',
        selectedIconPath: 'assets/tabbar/progress-selected.png',
      },
      {
        pagePath: 'pages/mine/index',
        text: '我的',
        iconPath: 'assets/tabbar/mine.png',
        selectedIconPath: 'assets/tabbar/mine-selected.png',
      },
    ],
  },
  // 微信隐私能力开关（2023-10-17 后默认启用；保留显式配置以兼容低版本基础库的提审调试）
  __usePrivacyCheck__: true,
} as any)
